---
title: "R Notebook"
output: html_notebook
---


```{r}
df <- read.delim("data/GP_metadata.txt")

df <- df %>%
  mutate(
    lat = as.numeric(sub(",.*", "", Lat_long)),
    long = as.numeric(sub(".*,", "", Lat_long))
  ) %>%
  filter(!is.na(lat), !is.na(long))


points_sf <- st_as_sf(df, coords = c("long", "lat"), crs = 4326)

hull <- st_convex_hull(st_union(points_sf))

uk <- ne_countries(scale = "medium", returnclass = "sf") %>% 
  filter(admin == "United Kingdom")

map_plot <- ggplot() +
  geom_sf(data = uk, fill = "gray95", color = "black") +
  geom_sf(data = hull, fill = "deepskyblue4", alpha = 0.4, color = "black") +
  theme_minimal() +
  coord_sf(expand = FALSE) 

ggsave("images/map_plot.png", map_plot, width = 6, height = 8, dpi = 300)
```


```{r}
library(ggplot2)
library(plotly)
library(dplyr)

df_ancom <- read.delim("data/ITS/Taxonomy/Taxonomic_Abundance/F03_Establishment_ancom/data/ancom.tsv")
df_data <- read.delim("data/ITS/Taxonomy/Taxonomic_Abundance/F03_Establishment_ancom/data/data.tsv")

df_data$X <- df_data$id
df_data <- df_data[, -1]
df <- left_join(df_ancom, df_data)

p <- ggplot(df, aes(x = clr, y = W, text = X)) +
  geom_point(aes(color = `Reject.null.hypothesis`)) +
  scale_color_manual(values = c("grey", "cyan3")) +
  theme_minimal() +
  labs(x = "Centered Logarithmic (clr)",
       y = "W statistic",
       title = "Volcano plot (ANCOM results)") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

ggplotly(p, tooltip = "text")

```



```{r}
library(readr)
library(dplyr)
library(tidyr)
library(leaflet)

# Charger les données
df_meta <- read_tsv("data/GP_metadata.txt", col_types = cols())

# Extraire lat/lon de la colonne "Lat_long"
df_meta <- df_meta %>%
  separate(Lat_long, into = c("Latitude", "Longitude"), sep = ", ", convert = TRUE)

# Ne garder qu'un seul point par site
df_sites <- df_meta %>%
  group_by(Site) %>%
  summarise(
    Latitude = first(Latitude),
    Longitude = first(Longitude),
    .groups = "drop"
  )

# Créer la carte
leaflet(df_sites) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircleMarkers(
    ~Longitude, ~Latitude,
    radius = 5,
    color = "darkblue",
    fillOpacity = 0.7,
    stroke = FALSE,
    label = ~Site,
    labelOptions = labelOptions(noHide = FALSE, direction = "auto")
  )
```












```{r}
df <- read.delim("data/16S/Beta_Diversity/bray_permanova_Year_group/data/raw_data.tsv")
df <- df[df$Group1 != "unknown" & df$Group2 != "unknown", ]



df_nat <- df %>%
  filter(Group1 == "1940-60" | Group2 == "1940-60") %>%
  mutate(
    Compared_to = ifelse(Group1 == "1940-60", Group2, Group1),
    Compared_to = factor(Compared_to, levels = c("1940-60", "1981-2000","2001-2010", "2011-2020"))
  )

plot1 <- ggplot(df_nat, aes(x = Compared_to, y = Distance, fill = Compared_to)) +
  geom_boxplot() +
  scale_fill_manual(values = c(
    "1940-60" = "#C6DBEF", 
    "1981-2000" = "#08519C", 
    "2001-2010" = "#3182BD",
    "2011-2020" = "skyblue"
  )) +
  theme_minimal() +
  labs(
    title = "Distance to group 1940-60",
    x = NULL,
    y = "Bray-Curtis Distance"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )

df_seed <- df %>%
  filter(Group1 == "1981-2000" | Group2 == "1981-2000") %>%
  mutate(
    Compared_to = ifelse(Group1 == "1981-2000", Group2, Group1),
    Compared_to = factor(Compared_to, levels = c("1981-2000", "1940-60", "2001-2010","2011-2020"))
  )

plot2 <- ggplot(df_seed, aes(x = Compared_to, y = Distance, fill = Compared_to)) +
  geom_boxplot() +
  scale_fill_manual(values = c(
    "1940-60" = "#C6DBEF", 
    "1981-2000" = "#08519C", 
    "2001-2010" = "#3182BD",
    "2011-2020" = "skyblue"
  ))+
  theme_minimal() +
  labs(
    title = "Distance to group 1981-2000",
    x = NULL,
    y = "Bray-Curtis Distance"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )


df_green <- df %>%
  filter(Group1 == "2001-2010" | Group2 == "2001-2010") %>%
  mutate(
    Compared_to = ifelse(Group1 == "2001-2010", Group2, Group1),
    Compared_to = factor(Compared_to, levels = c( "2001-2010","1940-60", "1981-2000", "2011-2020"))
  )

plot3 <- ggplot(df_green, aes(x = Compared_to, y = Distance, fill = Compared_to)) +
  geom_boxplot() +
  scale_fill_manual(values = c(
    "1940-60" = "#C6DBEF", 
    "1981-2000" = "#08519C", 
    "2001-2010" = "#3182BD",
    "2011-2020" = "skyblue"
  ))+
  theme_minimal() +
  labs(
    title = "Distance to group 2001-2010",
    x = NULL,
    y = "Bray-Curtis Distance"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )


df_g <- df %>%
  filter(Group1 == "2011-2020" | Group2 == "2011-2020") %>%
  mutate(
    Compared_to = ifelse(Group1 == "2011-2020", Group2, Group1),
    Compared_to = factor(Compared_to, levels = c( "2011-2020","1940-60", "1981-2000", "2001-2010"))
  )

plot4 <- ggplot(df_g, aes(x = Compared_to, y = Distance, fill = Compared_to)) +
  geom_boxplot() +
  scale_fill_manual(values = c(
    "1940-60" = "#C6DBEF", 
    "1981-2000" = "#08519C", 
    "2001-2010" = "#3182BD",
    "2011-2020" = "skyblue"
  ))+
  theme_minimal() +
  labs(
    title = "Distance to group 2011-2020",
    x = NULL,
    y = "Bray-Curtis Distance"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )



```

```{r}
library(cowplot)
title <- ggdraw() + draw_label("Bray-Curtis distances by Year Group", fontface = 'bold', size = 14)

combined_plot <- plot_grid(plot1, plot2, plot3,plot4, nrow = 1, align = "hv", labels = c("A", "B", "C", "D"))

final_plot <- plot_grid(title, combined_plot, ncol = 1, rel_heights = c(0.1, 1))

ggsave("images/permanova/Bray_Curtis/16S/bray_permanova_Year_group.png", final_plot, width = 14, height = 6, dpi = 300)
```



```{r}
df <- read.delim("data/16S/Beta_Diversity/bray_permanova_pH_group/data/raw_data.tsv")

df <- df[df$Group1 != "unknown" & df$Group2 != "unknown", ]

df_nat <- df %>%
  filter(Group1 == "no" | Group2 == "no") %>%
  mutate(
    Compared_to = ifelse(Group1 == "no", Group2, Group1),
    Compared_to = factor(Compared_to, levels = c("no", "yes"))
  )

plot3 <- ggplot(df_nat, aes(x = Compared_to, y = Distance, fill = Compared_to)) +
  geom_boxplot() +
  scale_fill_manual(values = c(
    "no" = "#C6DBEF", 
    "yes" = "#08519C"
  )) +
  theme_minimal() +
  labs(
    title = "Distance to No",
    x = NULL,
    y = "Bray-Curtis Distance"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )




df_seed <- df %>%
  filter(Group1 == "yes" | Group2 == "yes") %>%
  mutate(
    Compared_to = ifelse(Group1 == "yes", Group2, Group1),
    Compared_to = factor(Compared_to, levels = c("yes", "no"))
  )

plot1 <- ggplot(df_seed, aes(x = Compared_to, y = Distance, fill = Compared_to)) +
  geom_boxplot() +
  scale_fill_manual(values = c(
    "no" = "#C6DBEF", 
    "yes" = "#08519C"
  ))+
  theme_minimal() +
  labs(
    title = "Distance to Yes",
    x = NULL,
    y = "Bray-Curtis Distance"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )



title <- ggdraw() + draw_label("Bray-Curtis distances by Plough", fontface = 'bold', size = 14)

combined_plot <- plot_grid(plot1, plot3, nrow = 1, align = "hv", labels = c("A", "B"))

final_plot <- plot_grid(title, combined_plot, ncol = 1, rel_heights = c(0.1, 1))

ggsave("images/permanova/Bray_Curtis/16S/bray_permanova_Plough.png", final_plot, width = 14, height = 6, dpi = 300)
```




```{r barplot-16S, echo =FALSE, message=FALSE, warning=FALSE}
custom_blues <- c(
  "#08306B",  
  "#08519C",  
  "#3182BD",  
  "#6BAED6",  
  "#C6DBEF"
)

taxa_df <- read_csv("data/16S/Taxonomy/s10_taxa_barplot_by_site/data/level-2.csv")

meta_cols <- c("Site", "Age", "OS_location", "pH", "Year_est", "Lat_long", "Cutting","Cattle","Sheep", "Plough", "EC", "Establishment")

colnames(taxa_df)[1] <- "Site"

taxa_long <- taxa_df %>%
  pivot_longer(
    cols = -all_of(meta_cols),
    names_to = "Taxon",
    values_to = "Abundance"
  )

taxa_rel <- taxa_long %>%
  group_by(Site) %>%
  mutate(Abundance = Abundance / sum(Abundance, na.rm = TRUE)) %>%
  ungroup()

site_groups <- taxa_rel %>%
  distinct(Site, Establishment) %>%
  arrange(Establishment, Site)

site_order <- site_groups %>%
  pull(Site)

taxa_rel <- taxa_rel %>%
  mutate(Site = factor(Site, levels = site_order))



taxon_order <- taxa_rel %>%
  group_by(Taxon) %>%
  summarise(Total = sum(Abundance), .groups = "drop") %>%
  arrange(desc(Total)) %>%
  pull(Taxon)



group_breaks <- site_groups %>%
  group_by(Establishment) %>%
  summarise(n = n()) %>%
  mutate(position = cumsum(n) + 0.5) %>%
  filter(row_number() < n())

site_groups <- site_groups %>%
  mutate(Site = factor(Site, levels = unique(site_order)))

group_labels <- site_groups %>%
  group_by(Establishment) %>%
  summarise(position = median(as.numeric(Site)), .groups = "drop")


taxa_rel <- taxa_rel %>%
  mutate(Taxon = factor(Taxon, levels = taxon_order))


plot <- ggplot(taxa_rel, aes(x = Site, y = Abundance * 100, fill = Taxon)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = rep(custom_blues, length.out = n_distinct(taxa_rel$Taxon))) +
  geom_vline(data = group_breaks, aes(xintercept = position), linetype = "dashed", colour = "black") +
  geom_text(data = group_labels, aes(x = position, y = 105, label = Establishment),
            inherit.aes = FALSE, size = 3, fontface = "bold") +
  labs(
    x = "Site", 
    y = "Relative Abundance (%)", 
    fill = "Taxon", 
    title = "Relative abundance of taxa across sites at phylum level (16S), ordered by Establishment"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, size = 5),
    axis.ticks.x = element_blank(),
    legend.text = element_text(size = 5)
  )

ggplotly(plot)  %>% layout(width = 900, height = 500)



```



```{r}



```

